apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cqrs-orders-api
spec:
  to: {kind: Service, name: cqrs-orders-api}
  port: {targetPort: http}
  tls: {termination: edge, insecureEdgeTerminationPolicy: Redirect}
